apiVersion: v1
kind: Service
metadata:
  name: pokedex-api-service
  namespace: default
spec:
  selector:
    app: pokedex-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort