apiVersion: v1
kind: ConfigMap
metadata:
  name: pokedex-config
data:
  pokedex.json: |
    {
      "pokemon": [
        {
          "id": 1,
          "name": "Bulbasaur",
          "type": ["Grass", "Poison"]
        }
      ]
    }
